In [1]:
!pip install rapidfuzz --quiet

import pandas as pd
import numpy as np
from rapidfuzz import process, fuzz, distance
from collections import Counter, defaultdict
import time


# Настройка отображения
pd.set_option('display.max_rows', 100)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 38.4 MB/s eta 0:00:0000:0100:01

In [2]:
print("=== ЗАГРУЗКА ЧИСТЫХ ДАННЫХ ===")
# Загружаем результаты прошлого ноутбука
orcs = pd.read_parquet('/kaggle/input/aim-orcs-precleaning/orcs_clean.parquet')
employees = pd.read_parquet('/kaggle/input/aim-orcs-precleaning/employees_clean.parquet')

print(f"Orcs: {orcs.shape}")
print(f"Employees: {employees.shape}")

=== ЗАГРУЗКА ЧИСТЫХ ДАННЫХ ===
Orcs: (47633, 7)
Employees: (2011759, 7)

In [ ]:
def build_vocab_stats(df_list, col):
    """
    Собирает все значения из колонки col во всех датафреймах
    и строит частотный словарь.
    """
    all_values = []
    for df in df_list:
        if col in df.columns:
            # Берем только непустые значения
            vals = df[col]
            vals = vals[vals != ""].tolist()
            all_values.extend(vals)

    # Считаем частоты
    counter = Counter(all_values)
    vocab_df = pd.DataFrame.from_dict(counter, orient='index', columns=['count']).reset_index()
    vocab_df = vocab_df.rename(columns={'index': 'word'})

    # Сортируем: сначала самые частые
    vocab_df = vocab_df.sort_values('count', ascending=False).reset_index(drop=True)

    return vocab_df

# Пример анализа для Имен
print("=== СТАТИСТИКА ПО ИМЕНАМ ===")
vocab_names = build_vocab_stats([orcs, employees], 'name')

print(f"Всего уникальных имен: {len(vocab_names)}")
print("Топ-10 частых:")
display(vocab_names.head(10))

print("Топ-10 редких (хвост):")
display(vocab_names.tail(10))

# Посмотрим на распределение (сколько имен встречаются 1 раз?)
singletons = vocab_names[vocab_names['count'] == 1].shape[0]
print(f"\nИмен, встречающихся ровно 1 раз: {singletons} ({singletons/len(vocab_names):.1%} от уникальных)")

=== СТАТИСТИКА ПО ИМЕНАМ ===
Всего уникальных имен: 218363
Топ-10 частых:

        word  count
0  александр  53133
1     сергей  45393
2    татьяна  43663
3      елена  41650
4      ольга  33978
5    наталья  33606
6   владимир  31756
7    алексей  29222
8       анна  28736
9  валентина  25853

Топ-10 редких (хвост):

             word  count
218353     дурние      1
218354    зинуиха      1
218355   армуллох      1
218356    а*еилна      1
218357      лилуя      1
218358    натал*ь      1
218359    гоухара      1
218360   хнатолий      1
218361  нуржигана      1
218362      мкьюя      1

Имен, встречающихся ровно 1 раз: 151173 (69.2% от уникальных)

In [ ]:
def generate_correction_map_waterfall(vocab_df, ### <--- 2. Имя функции упростили
                                      thresholds=[50000, 10000, 5000, 2000, 500, 100, 20, 0],
                                      min_ratio=9.0,
                                      cutoff_base=0.65,
                                      use_blocking=False, ### <--- 3. Флаг Блокировки
                                      use_delay=True):

    print(f"Запуск ВОДОПАДА (Cutoff {cutoff_base}, Ratio {min_ratio})...")

    correction_map = {}

    # 1. Инициализация
    top_threshold = thresholds[0]
    mask_clean = ~vocab_df['word'].str.contains(r'\*', regex=True)
    mask_len = vocab_df['word'].str.len() > 2

    current_targets_df = vocab_df[(vocab_df['count'] > top_threshold) & mask_clean & mask_len]
    current_targets = set(current_targets_df['word'].values)

    freq_dict = dict(zip(vocab_df['word'], vocab_df['count']))

    dormant_targets = []

    print(f"Базовых эталонов: {len(current_targets)}")

    # 2. Проход по уровням
    for i in range(len(thresholds) - 1):
        high = thresholds[i]
        low = thresholds[i+1]

        if use_delay:
            # Эталон должен быть больше жертвы в min_ratio раз. Макс. жертва сейчас = high.
            min_needed_freq = high * min_ratio

            # Переносим из dormant в active тех, кто проходит порог
            waking_up = [w for w in dormant_targets if freq_dict[w] >= min_needed_freq]
            dormant_targets = [w for w in dormant_targets if freq_dict[w] < min_needed_freq]

            current_targets.update(waking_up)
            if waking_up:
                print(f"  [Delay] Активировано {len(waking_up)} эталонов (Freq >= {min_needed_freq:.0f})")

        mask_range = (vocab_df['count'] > low) & (vocab_df['count'] <= high)
        candidates_df = vocab_df[mask_range & mask_len]
        all_candidates = candidates_df['word'].values

        if len(all_candidates) == 0: continue

        if use_blocking:
            targets_by_char = defaultdict(list)
            for t in current_targets:
                targets_by_char[t[0]].append(t)
            targets_list_all = list(current_targets) # Fallback для слов со звездочкой
        else:
            targets_list = list(current_targets)

        survivors = []
        fixed_count = 0

        for candidate in all_candidates:
            # ДИНАМИЧЕСКИЙ CUTOFF
            # Звезды всегда матчим чуть мягче (-0.05), так как * съедает информацию
            current_cutoff = (cutoff_base - 0.05) if '*' in candidate else cutoff_base

            if use_blocking:
                # Если в слове есть *, мы не знаем первую букву наверняка -> ищем везде
                if '*' in candidate:
                    targets_subset = targets_list_all
                else:
                    first_char = candidate[0]
                    targets_subset = targets_by_char.get(first_char, [])
            else:
                targets_subset = targets_list

            # Если список пуст, искать нечего
            if not targets_subset:
                if '*' not in candidate: survivors.append(candidate)
                continue

            match = process.extractOne(
                candidate,
                targets_subset,
                scorer=distance.DamerauLevenshtein.normalized_similarity,
                score_cutoff=current_cutoff
            )

            is_fixed = False

            if match:
                best_word, score, _ = match
                f_cand = freq_dict[candidate]
                f_targ = freq_dict[best_word]

                # Ratio Check
                ratio = f_targ / f_cand if f_cand > 0 else 9999

                if ratio >= min_ratio:
                    dist = distance.DamerauLevenshtein.distance(candidate, best_word)

                    # Distance Check
                    valid_dist = False
                    if '*' in candidate:
                        if dist == 1: valid_dist = True
                        elif dist == 2 and len(candidate) >= 5: valid_dist = True
                    else:
                        if dist == 1: valid_dist = True
                        elif dist == 2 and len(candidate) >= 6: valid_dist = True

                    if valid_dist:
                        correction_map[candidate] = {
                            'correct': best_word,
                            'dist': dist,
                            'score': score
                        }
                        is_fixed = True
                        fixed_count += 1

            if not is_fixed and '*' not in candidate:
                survivors.append(candidate)

        if use_delay:
            dormant_targets.extend(survivors)
        else:
            current_targets.update(survivors)
        print(f"  Уровень {low}-{high}: Исправлено {fixed_count}. Стали новыми эталонами: {len(survivors)}")

    print(f"Поиск завершен. Найдено {len(correction_map)} пар.")

    return correction_map

correction_map_names = generate_correction_map_waterfall(
    vocab_names,
    thresholds=[10000, 5000, 2000, 500, 100, 20, 0],
    min_ratio=9.0,
    cutoff_base=0.7,
    use_blocking=False,
    use_delay=True,
)

Запуск ВОДОПАДА (Cutoff 0.7, Ratio 9.0)...
Базовых эталонов: 35
  Уровень 5000-10000: Исправлено 0. Стали новыми эталонами: 23
  Уровень 2000-5000: Исправлено 18. Стали новыми эталонами: 30
  Уровень 500-2000: Исправлено 150. Стали новыми эталонами: 55
  [Delay] Активировано 28 эталонов (Freq >= 4500)
  Уровень 100-500: Исправлено 669. Стали новыми эталонами: 163
  [Delay] Активировано 43 эталонов (Freq >= 900)
  Уровень 20-100: Исправлено 889. Стали новыми эталонами: 779
  [Delay] Активировано 110 эталонов (Freq >= 180)
  Уровень 0-20: Исправлено 47220. Стали новыми эталонами: 145029
Поиск завершен. Найдено 48946 пар.

In [ ]:
def preview_correction_map_fast(vocab_df, correction_map, limit=100):
    if not correction_map:
        print("Карта пуста.")
        return

    print("Подготовка быстрого словаря частот...")
    # Превращаем DataFrame в словарь {слово: частота} -> это O(1) доступ
    freq_dict = dict(zip(vocab_df['word'], vocab_df['count']))

    print(f"Обработка {len(correction_map)} исправлений...")

    preview_data = []

    for wrong, data in correction_map.items():
        correct = data['correct']

        count_wrong = freq_dict.get(wrong, 0)
        count_correct = freq_dict.get(correct, 0)

        preview_data.append({
            'Original': wrong,
            'Fixed': correct,
            'Dist': data['dist'],
            'Freq_Orig': count_wrong,
            'Freq_Fix': count_correct,
            'Ratio': round(count_correct / count_wrong, 1) if count_wrong > 0 else 0
        })

    df_preview = pd.DataFrame(preview_data)

    # Сортируем: показываем те исправления, которые затронут больше всего строк (Freq_Orig)
    # И где дистанция минимальна
    df_preview = df_preview.sort_values(['Dist', 'Freq_Orig'], ascending=[True, False])

    print(f"=== ПРЕДПРОСМОТР ИСПРАВЛЕНИЙ (Топ-{limit}) ===")
    display(df_preview.head(limit))

    return df_preview

df_preview_names = preview_correction_map_fast(vocab_names, correction_map_names, limit=100)

Подготовка быстрого словаря частот...
Обработка 48946 исправлений...
=== ПРЕДПРОСМОТР ИСПРАВЛЕНИЙ (Топ-100) ===

       Original       Fixed  Dist  Freq_Orig  Freq_Fix  Ratio
0     олександр   александр     1       4274     53133   12.4
1         алена       елена     1       3458     41650   12.0
2         елено       елена     1       3441     41650   12.1
3       тотьяна     татьяна     1       3348     43663   13.0
4       ноталья     наталья     1       2761     33606   12.2
5         ольго       ольга     1       2721     33978   12.5
6      влодимир    владимир     1       2697     31756   11.8
7      владемир    владимир     1       2632     31756   12.1
8       олексей     алексей     1       2392     29222   12.2
9          онна        анна     1       2247     28736   12.8
10    валентена   валентина     1       2206     25853   11.7
11    волентина   валентина     1       2133     25853   12.1
12        марея       мария     1       2114     25013   11.8
13        мория       мария     1       2108     25013   11.9
14      неколай     николай     1       2086     23993   11.5
15        ерина       ирина     1       2067     25091   12.1
16        ирино       ирина     1       2067     25091   12.1
17      николой     николай     1       2046     23993   11.7
18     светлона    светлана     1       1969     25331   12.9
19       галена      галина     1       1921     22404   11.7
20       голина      галина     1       1826     22404   12.3
21       ондрей      андрей     1       1799     21984   12.2
22    екотерина   екатерина     1       1731     20333   11.7
23      дметрий     дмитрий     1       1728     21406   12.4
24    екатерена   екатерина     1       1719     20333   11.8
25          нна        нина     1       1681     18596   11.1
26      людмела     людмила     1       1657     18891   11.4
27      нодежда     надежда     1       1655     20760   12.5
28         нена        нина     1       1584     18596   11.7
29       вектор      виктор     1       1578     19578   12.4
30         нино        нина     1       1548     18596   12.0
31        жанна        анна     1       1543     28736   18.6
32         лена       елена     1       1540     41650   27.0
33      людмило     людмила     1       1509     18891   12.5
34       михоил      михаил     1       1403     16740   11.9
35       мехаил      михаил     1       1400     16740   12.0
36         юлея        юлия     1       1388     16447   11.8
38      евгеней     евгений     1       1300     15737   12.1
39         юрей        юрий     1       1297     16485   12.7
40        сргей      сергей     1       1241     45393   36.6
41    анастасея   анастасия     1       1238     15290   12.4
42          ана        анна     1       1233     28736   23.3
43       марена      марина     1       1217     13918   11.4
44    онастасия   анастасия     1       1202     15290   12.7
45        арина      марина     1       1163     13918   12.0
46        елеан       елена     1       1151     41650   36.2
47        елнеа       елена     1       1127     41650   37.0
48         анан        анна     1       1127     28736   25.5
49         ивон        иван     1       1101     12639   11.5
50       морина      марина     1       1100     13918   12.7
51        еелна       елена     1       1092     41650   38.1
52         еван        иван     1       1056     12639   12.0
53   олександра  александра     1       1043     13022   12.5
54     анатолей    анатолий     1       1019     12253   12.0
55          ина        нина     1        994     18596   18.7
56       ттьяна     татьяна     1        991     43663   44.1
57     онатолий    анатолий     1        989     12253   12.4
58        ледия       лидия     1        982     12551   12.8
59        егорь       игорь     1        962     12100   12.6
60     лександр   александр     1        945     53133   56.2
61       атьяна     татьяна     1        934     43663   46.7
62        ольаг       ольга     1        920     33978   36.9
63       срегей      сергей     1        914     45393   49.7
64        оьлга       ольга     1        908     33978   37.4
65         веро        вера     1        889     11289   12.7
66        еле*а       елена     1        875     41650   47.6
67       карина      марина     1        873     13918   15.9
68        олгьа       ольга     1        870     33978   39.1
69         рина       ирина     1        859     25091   29.2
70       серегй      сергей     1        857     45393   53.0
71       сергйе      сергей     1        855     45393   53.1
72        елен*       елена     1        853     41650   48.8
73       сегрей      сергей     1        847     45393   53.6
74        е*ена       елена     1        821     41650   50.7
75        ел*на       елена     1        807     41650   51.6
76       нталья     наталья     1        796     33606   42.2
77         ниан        нина     1        794     18596   23.4
78         анн*        анна     1        791     28736   36.3
79         нниа        нина     1        775     18596   24.0
80        ол*га       ольга     1        752     33978   45.2
81         ан*а        анна     1        743     28736   38.7
82         а*на        анна     1        738     28736   38.9
83         юирй        юрий     1        734     16485   22.5
84        иирна       ирина     1        729     25091   34.4
85       алксей     алексей     1        725     29222   40.3
86        ольг*       ольга     1        717     33978   47.4
87      татьяан     татьяна     1        707     43663   61.8
88       се*гей      сергей     1        706     45393   64.3
89        маряи       мария     1        705     25013   35.5
90      ттаьяна     татьяна     1        703     43663   62.1
91        глина      галина     1        702     22404   31.9
92         елен       елена     1        700     41650   59.5
93       сер*ей      сергей     1        700     45393   64.8
94        мраия       мария     1        693     25013   36.1
95        ириан       ирина     1        692     25091   36.3
96        маиря       мария     1        691     25013   36.2
97       серге*      сергей     1        690     45393   65.8
98        оль*а       ольга     1        684     33978   49.7
99        ирниа       ирина     1        682     25091   36.8
100        еена       елена     1        678     41650   61.4

In [ ]:
def audit_correction_ratios(vocab_df, correction_map, low_threshold=2.0):
    print(f"Аудит {len(correction_map)} исправлений...")

    # Быстрый словарь частот
    freq_dict = dict(zip(vocab_df['word'], vocab_df['count']))

    audit_data = []

    for wrong, data in correction_map.items():
        correct = data['correct']
        f_wrong = freq_dict.get(wrong, 0)
        f_correct = freq_dict.get(correct, 0)

        ratio = f_correct / f_wrong if f_wrong > 0 else 9999

        audit_data.append({
            'wrong': wrong,
            'correct': correct,
            'f_wrong': f_wrong,
            'f_correct': f_correct,
            'ratio': round(ratio, 2)
        })

    df_audit = pd.DataFrame(audit_data)

    # Статистика
    print(f"Мин. Ratio: {df_audit['ratio'].min()}")
    print(f"Макс. Ratio: {df_audit['ratio'].max()}")
    print(f"Медиана Ratio: {df_audit['ratio'].median()}")

    # Опасная зона
    risky = df_audit[df_audit['ratio'] < low_threshold]
    print(f"\n⚠️ Исправлений с Ratio < {low_threshold}: {len(risky)} шт.")

    if len(risky) > 0:
        print("Примеры 'на грани' (низкий перевес):")
        display(risky.sort_values('ratio').head(20))
    else:
        print("✅ Все исправления имеют сильный перевес частоты!")

    return df_audit

# АУДИТ
# Проверяем, исчезли ли ratio < 9.0 и появились ли 'никлой'/'мехаел'
_ = audit_correction_ratios(vocab_names, correction_map_names, low_threshold=10.0)

Аудит 48946 исправлений...
Мин. Ratio: 9.2
Макс. Ratio: 53133.0
Медиана Ratio: 4567.0

⚠️ Исправлений с Ratio < 10.0: 5 шт.
Примеры 'на грани' (низкий перевес):

         wrong    correct  f_wrong  f_correct  ratio
1737  прсковья  просковья       20        184   9.20
1752   дильбар     ильдар       20        185   9.25
1836   арменак      армен       19        180   9.47
1773      лара      клара       20        190   9.50
1797      леля       неля       19        185   9.74

In [ ]:
def apply_corrections_verbose(df, col, mapping, df_name="DataFrame"):
    """
    Применяет исправления и выводит статистику:
    - Сколько строк затронуто.
    - Как изменилось количество уникальных значений.
    """
    # 1. Превращаем "богатую" карту (с dist/score) в простую {bad: good}
    simple_map = {k: v['correct'] for k, v in mapping.items()}

    if not simple_map:
        print(f"⚠️ {df_name}: Карта исправлений пуста. Изменений нет.")
        return df

    # 2. Метрики ДО
    unique_before = df[col].nunique()

    # 3. Вычисляем маску (кого будем менять)
    mask = df[col].isin(simple_map.keys())
    affected_count = mask.sum()

    # 4. Применяем
    if affected_count > 0:
        # Используем .map только для нужных строк (быстро)
        df.loc[mask, col] = df.loc[mask, col].map(simple_map)

    # 5. Метрики ПОСЛЕ
    unique_after = df[col].nunique()
    diff = unique_before - unique_after

    # 6. Отчет
    print(f"=== ПРИМЕНЕНИЕ: {df_name} [{col}] ===")
    print(f"  📝 Строк изменено:      {affected_count}")
    print(f"  📊 Уникальных ДО:       {unique_before}")
    print(f"  📊 Уникальных ПОСЛЕ:    {unique_after}")
    if diff > 0:
        print(f"  📉 Сжатие словаря:      -{diff} (столько дублей устранено)")
    else:
        print(f"  😐 Словарь не изменился (странно, если были замены)")
    print("-" * 30)

    return df

# ПРИМЕНЯЕМ К ИМЕНАМ (correction_map_names уже готов)
orcs = apply_corrections_verbose(orcs, 'name', correction_map_names, "ORCS")
employees = apply_corrections_verbose(employees, 'name', correction_map_names, "EMPLOYEES")

=== ПРИМЕНЕНИЕ: ORCS [name] ===
  📝 Строк изменено:      6947
  📊 Уникальных ДО:       32398
  📊 Уникальных ПОСЛЕ:    28356
  📉 Сжатие словаря:      -4042 (столько дублей устранено)
------------------------------
=== ПРИМЕНЕНИЕ: EMPLOYEES [name] ===
  📝 Строк изменено:      494441
  📊 Уникальных ДО:       206517
  📊 Уникальных ПОСЛЕ:    158307
  📉 Сжатие словаря:      -48210 (столько дублей устранено)
------------------------------

In [ ]:
print("=== СТАТИСТИКА ПО ОТЧЕСТВАМ ===")
vocab_fath = build_vocab_stats([orcs, employees], 'fathername')
print(f"Всего уникальных: {len(vocab_fath)}")

# ГЕНЕРАЦИЯ (Водопад)
# Отчества - шаблонные. Ставим cutoff_base=0.75 (помягче),
# так как длина слова обычно большая.
correction_map_fath = generate_correction_map_waterfall(
    vocab_fath,
    thresholds=[10000, 5000, 2000, 500, 100, 20, 0],
    min_ratio=9.0,
    cutoff_base=0.67,
    use_blocking=False,
    use_delay=True,
)

# ПРЕВЬЮ
print("\n=== ПРЕДПРОСМОТР ОТЧЕСТВ ===")
_ = preview_correction_map_fast(vocab_fath, correction_map_fath, limit=100)

=== СТАТИСТИКА ПО ОТЧЕСТВАМ ===
Всего уникальных: 436579
Запуск ВОДОПАДА (Cutoff 0.67, Ratio 9.0)...
Базовых эталонов: 21
  Уровень 5000-10000: Исправлено 0. Стали новыми эталонами: 25
  Уровень 2000-5000: Исправлено 0. Стали новыми эталонами: 52
  Уровень 500-2000: Исправлено 182. Стали новыми эталонами: 95
  [Delay] Активировано 31 эталонов (Freq >= 4500)
  Уровень 100-500: Исправлено 805. Стали новыми эталонами: 230
  [Delay] Активировано 99 эталонов (Freq >= 900)
  Уровень 20-100: Исправлено 2132. Стали новыми эталонами: 565
  [Delay] Активировано 124 эталонов (Freq >= 180)
  Уровень 0-20: Исправлено 141442. Стали новыми эталонами: 238738
Поиск завершен. Найдено 144561 пар.

=== ПРЕДПРОСМОТР ОТЧЕСТВ ===
Подготовка быстрого словаря частот...
Обработка 144561 исправлений...
=== ПРЕДПРОСМОТР ИСПРАВЛЕНИЙ (Топ-100) ===

          Original          Fixed  Dist  Freq_Orig  Freq_Fix  Ratio
0     лександровна  александровна     1       1762     40751   23.1
1         сргеевна      сергеевна     1       1736     27555   15.9
2          ивновна       ивановна     1       1408     25733   18.3
3         сргеевич      сергеевич     1       1383     22693   16.4
4          иваовна       ивановна     1       1359     25733   18.9
5        иколаевна     николаевна     1       1288     29379   22.8
6          иановна       ивановна     1       1276     25733   20.2
7        николевна     николаевна     1       1230     29379   23.9
8     алексадровна  александровна     1       1188     40751   34.3
9        алксеевна     алексеевна     1       1153     20799   18.0
10     владмирович   владимирович     1       1111     21789   19.6
11       нколаевич     николаевич     1       1009     22738   22.5
12     влдимировна   владимировна     1        967     25743   26.6
13     ладимировна   владимировна     1        947     25743   27.2
14    лександрович  александрович     1        944     27723   29.4
15     владмировна   владимировна     1        914     25743   28.2
16        иванонва       ивановна     1        907     25733   28.4
17        иванвона       ивановна     1        906     25733   28.4
18        иванован       ивановна     1        889     25733   28.9
19         ванович       иванович     1        884     16549   18.7
20        иваонвна       ивановна     1        878     25733   29.3
21        иавновна       ивановна     1        855     25733   30.1
22         ианович       иванович     1        853     16549   19.4
23       алксеевич     алексеевич     1        846     13699   16.2
24        ивнаовна       ивановна     1        841     25733   30.6
25        ив*новна       ивановна     1        816     25733   31.5
26        ива*овна       ивановна     1        790     25733   32.6
27      нкиолаевна     николаевна     1        788     29379   37.3
28      николавена     николаевна     1        771     29379   38.1
29      ниоклаевна     николаевна     1        767     29379   38.3
30      николаеван     николаевна     1        762     29379   38.6
31      никоалевна     николаевна     1        755     29379   38.9
32       лексеевна     алексеевна     1        752     20799   27.7
33       серегевна      сергеевна     1        751     27555   36.7
34        иван*вна       ивановна     1        749     25733   34.4
35       михйловна     михайловна     1        746     17662   23.7
36      николаенва     николаевна     1        743     29379   39.5
37       срегеевна      сергеевна     1        743     27555   37.1
38        ивановн*       ивановна     1        742     25733   34.7
39      никол*евна     николаевна     1        739     29379   39.8
40       сергевена      сергеевна     1        739     27555   37.3
41        ивано*на       ивановна     1        733     25733   35.1
42     ладимирович   владимирович     1        731     21789   29.8
43      н*колаевна     николаевна     1        730     29379   40.2
44        и*ановна       ивановна     1        724     25733   35.5
45       нколаевна     николаевна     1        719     29379   40.9
46      николеавна     николаевна     1        718     29379   40.9
47       всильевна     васильевна     1        717     14810   20.7
48         вановна       ивановна     1        715     25733   36.0
49   александронва  александровна     1        713     40751   57.2
50      никлоаевна     николаевна     1        711     29379   41.3
51       асильевна     васильевна     1        709     14810   20.9
52       сергеенва      сергеевна     1        705     27555   39.1
53      нико*аевна     николаевна     1        704     29379   41.7
54        иванов*а       ивановна     1        704     25733   36.6
55   алекасндровна  александровна     1        703     40751   58.0
56   александрован  александровна     1        691     40751   59.0
57       сергеевн*      сергеевна     1        691     27555   39.9
58      натольевна    анатольевна     1        691     11732   17.0
59       сергее*на      сергеевна     1        689     27555   40.0
60      николаев*а     николаевна     1        688     29379   42.7
61       сегреевна      сергеевна     1        686     27555   40.2
62       виктровна     викторовна     1        679     16018   23.6
63       икторовна     викторовна     1        676     16018   23.7
64   александорвна  александровна     1        673     40751   60.6
65   александрвона  александровна     1        673     40751   60.6
66         иванвна       ивановна     1        670     25733   38.4
67      николаевн*     николаевна     1        669     29379   43.9
68      ник*лаевна     николаевна     1        666     29379   44.1
69      николае*на     николаевна     1        666     29379   44.1
70   аелксандровна  александровна     1        664     40751   61.4
71   алексаднровна  александровна     1        662     40751   61.6
72   александровн*  александровна     1        661     40751   61.7
73       сергееван      сергеевна     1        656     27555   42.0
74   александро*на  александровна     1        655     40751   62.2
75      ни*олаевна     николаевна     1        655     29379   44.9
76   алкесандровна  александровна     1        654     40751   62.3
77   алексанрдовна  александровна     1        653     40751   62.4
78   алекснадровна  александровна     1        651     40751   62.6
79   ал*ксандровна  александровна     1        646     40751   63.1
80      никола*вна     николаевна     1        644     29379   45.6
81       сергеев*а      сергеевна     1        643     27555   42.9
82   алексан*ровна  александровна     1        642     40751   63.5
83   александр*вна  александровна     1        640     40751   63.7
84       николаена     николаевна     1        638     29379   46.0
85       никлаевна     николаевна     1        638     29379   46.0
86   алекс*ндровна  александровна     1        637     40751   64.0
87   александ*овна  александровна     1        635     40751   64.2
88   алескандровна  александровна     1        631     40751   64.6
89   а*ександровна  александровна     1        627     40751   65.0
90       икторович     викторович     1        625     16246   26.0
91       ниолаевна     николаевна     1        622     29379   47.2
92        сергеена      сергеевна     1        622     27555   44.3
94   алек*андровна  александровна     1        619     40751   65.8
95       се*геевна      сергеевна     1        617     27555   44.7
96       виктрович     викторович     1        614     16246   26.5
97    александрона  александровна     1        614     40751   66.4
98       никоаевна     николаевна     1        614     29379   47.8
99       серегевич      сергеевич     1        613     22693   37.0
100      николавна     николаевна     1        612     29379   48.0

In [ ]:
def audit_risky_corrections(correction_map):
    print("=== АУДИТ РИСКОВАННЫХ ИСПРАВЛЕНИЙ ===")

    ogly_loss = []
    gender_swap = []

    for wrong, data in correction_map.items():
        correct = data['correct']

        # 1. Проверка потери Оглы/Кызы
        has_ogly_wrong = 'оглы' in wrong or 'кызы' in wrong
        has_ogly_right = 'оглы' in correct or 'кызы' in correct

        if has_ogly_wrong and not has_ogly_right:
            ogly_loss.append((wrong, correct))

        # 2. Проверка смены пола (Вич <-> Вна)
        # Грубая проверка по окончанию, но эффективная
        is_male_wrong = wrong.endswith('вич')
        is_female_wrong = wrong.endswith('вна')

        is_male_right = correct.endswith('вич')
        is_female_right = correct.endswith('вна')

        if (is_male_wrong and is_female_right) or (is_female_wrong and is_male_right):
            gender_swap.append((wrong, correct))

    print(f"⚠️ Потеря 'оглы/кызы': {len(ogly_loss)} шт.")
    if len(ogly_loss) > 0:
        print(f"   Примеры: {ogly_loss[:10]}")

    print(f"⚠️ Смена пола (вич/вна): {len(gender_swap)} шт.")
    if len(gender_swap) > 0:
        print(f"   Примеры: {gender_swap[:10]}")

    if len(ogly_loss) == 0 and len(gender_swap) == 0:
        print("✅ Критических ошибок не найдено.")

# Запуск аудита
audit_risky_corrections(correction_map_fath)

=== АУДИТ РИСКОВАННЫХ ИСПРАВЛЕНИЙ ===
⚠️ Потеря 'оглы/кызы': 0 шт.
⚠️ Смена пола (вич/вна): 0 шт.
✅ Критических ошибок не найдено.

In [10]:
# ПРИМЕНЯЕМ К отчествам (correction_map_names уже готов)
orcs = apply_corrections_verbose(orcs, 'fathername', correction_map_fath, "ORCS")
employees = apply_corrections_verbose(employees, 'fathername', correction_map_fath, "EMPLOYEES")

=== ПРИМЕНЕНИЕ: ORCS [fathername] ===
  📝 Строк изменено:      8889
  📊 Уникальных ДО:       39325
  📊 Уникальных ПОСЛЕ:    32674
  📉 Сжатие словаря:      -6651 (столько дублей устранено)
------------------------------
=== ПРИМЕНЕНИЕ: EMPLOYEES [fathername] ===
  📝 Строк изменено:      715213
  📊 Уникальных ДО:       412877
  📊 Уникальных ПОСЛЕ:    270474
  📉 Сжатие словаря:      -142403 (столько дублей устранено)
------------------------------

In [ ]:
print("=== СТАТИСТИКА ПО ФАМИЛИЯМ ===")
vocab_sur = build_vocab_stats([orcs, employees], 'surname')
print(f"Всего уникальных: {len(vocab_sur)}")

# ГЕНЕРАЦИЯ (Строгий режим)
# Cutoff 0.85 - чтобы не спутать "Иванов" и "Иванков"
# Ratio 9.0 - меняем только явный мусор на явных лидеров
correction_map_sur = generate_correction_map_waterfall(
    vocab_sur,
    thresholds=[10000, 5000, 2000, 500, 100, 20, 0],
    min_ratio=9.0,
    cutoff_base=0.75,
    use_blocking=True,
    use_delay=True,
)

# ПРЕВЬЮ
print("\n=== ПРЕДПРОСМОТР ФАМИЛИЙ (Топ-100) ===")
_ = preview_correction_map_fast(vocab_sur, correction_map_sur, limit=100)

=== СТАТИСТИКА ПО ФАМИЛИЯМ ===
Всего уникальных: 911732
Запуск ВОДОПАДА (Cutoff 0.75, Ratio 9.0)...
Базовых эталонов: 0
  Уровень 2000-5000: Исправлено 0. Стали новыми эталонами: 4
  Уровень 500-2000: Исправлено 0. Стали новыми эталонами: 127
  Уровень 100-500: Исправлено 0. Стали новыми эталонами: 1159
  [Delay] Активировано 46 эталонов (Freq >= 900)
  Уровень 20-100: Исправлено 917. Стали новыми эталонами: 6050
  [Delay] Активировано 565 эталонов (Freq >= 180)
  Уровень 0-20: Исправлено 94672. Стали новыми эталонами: 665188
Поиск завершен. Найдено 95589 пар.

=== ПРЕДПРОСМОТР ФАМИЛИЙ (Топ-100) ===
Подготовка быстрого словаря частот...
Обработка 95589 исправлений...
=== ПРЕДПРОСМОТР ИСПРАВЛЕНИЙ (Топ-100) ===

      Original      Fixed  Dist  Freq_Orig  Freq_Fix  Ratio
0       влкова    волкова     1         99      1619   16.4
1      ив*нова    иванова     1         98      2624   26.8
2      ивнаова    иванова     1         97      2624   27.1
3      мрозова   морозова     1         97      1394   14.4
4      иваонва    иванова     1         95      2624   27.6
6       и*анов     иванов     1         94      2060   21.9
7       иван*в     иванов     1         92      2060   22.4
8       иавнов     иванов     1         92      2060   22.4
9      ивано*а    иванова     1         90      2624   29.2
10     иванов*    иванова     1         90      2624   29.2
11     и*анова    иванова     1         90      2624   29.2
12      сколов    соколов     1         90      1090   12.1
13     иван*ва    иванова     1         89      2624   29.5
14      мрозов    морозов     1         87      1216   14.0
15        ппов      попов     1         86      1447   16.8
16     мкарова   макарова     1         86      1230   14.3
18   кузнцеова  кузнецова     1         84      2805   33.4
19       иваов     иванов     1         84      2060   24.5
20       кзлов     козлов     1         84      1420   16.9
21       попо*      попов     1         83      1447   17.4
22       влков     волков     1         82      1506   18.4
23      ивано*     иванов     1         81      2060   25.4
24      поопва     попова     1         81      1579   19.5
25    новичков    новиков     1         80      1179   14.7
26   кузенцова  кузнецова     1         80      2805   35.1
27    кузнецво   кузнецов     1         79      2492   31.5
28   кузнецвоа  кузнецова     1         79      2805   35.5
29       ппоов      попов     1         79      1447   18.3
30   кузнецоав  кузнецова     1         79      2805   35.5
31     смиронв    смирнов     1         79      1807   22.9
32   новичкова   новикова     1         78      1254   16.1
35      кзолов     козлов     1         77      1420   18.4
36    кунзецов   кузнецов     1         76      2492   32.8
37     зхарова   захарова     1         76      1145   15.1
38    розанова   романова     1         76      1062   14.0
39       поопв      попов     1         75      1447   19.3
40   к*знецова  кузнецова     1         75      2805   37.4
42   кунзецова  кузнецова     1         75      2805   37.4
43       попво      попов     1         74      1447   19.6
44      иваонв     иванов     1         74      2060   27.8
45   кузне*ова  кузнецова     1         74      2805   37.9
46   куз*ецова  кузнецова     1         74      2805   37.9
48    сминрова   смирнова     1         73      1885   25.8
49     лбедева   лебедева     1         73       929   12.7
50      иванва    иванова     1         73      2624   35.9
51    кузнецо*   кузнецов     1         73      2492   34.1
52      понова     попова     1         73      1579   21.6
53   кузнецов*  кузнецова     1         72      2805   39.0
54    степнова  степанова     1         72       988   13.7
55      ноиков    новиков     1         71      1179   16.6
56    кузенцов   кузнецов     1         71      2492   35.1
57       иванв     иванов     1         71      2060   29.0
58     ноикова   новикова     1         71      1254   17.7
61      иваова    иванова     1         70      2624   37.5
62   кузн*цова  кузнецова     1         70      2805   40.1
63    смирнвоа   смирнова     1         70      1885   26.9
64      ива*ов     иванов     1         69      2060   29.9
65     смирнво    смирнов     1         69      1807   26.2
66    симрнова   смирнова     1         69      1885   27.3
67    кузнцеов   кузнецов     1         69      2492   36.1
68   кузнецо*а  кузнецова     1         69      2805   40.7
69    смирноав    смирнов     1         69      1807   26.2
70      попоав      попов     1         68      1447   21.3
72      попвоа     попова     1         68      1579   23.2
73      ппоова     попова     1         68      1579   23.2
74      кзлова    козлова     1         68      1445   21.2
75       ивнов     иванов     1         68      2060   30.3
76    к*знецов   кузнецов     1         67      2492   37.2
78      петорв     петров     1         67      1347   20.1
79    кузнеоцв   кузнецов     1         67      2492   37.2
80    смирн*ва   смирнова     1         67      1885   28.1
81     волчков     волков     1         66      1506   22.8
82    ромашова   романова     1         66      1062   16.1
83   кузнеоцва  кузнецова     1         66      2805   42.5
84       поп*в      попов     1         66      1447   21.9
85     смирнва   смирнова     1         65      1885   29.0
86     волквоа    волкова     1         65      1619   24.9
87       егров     егоров     1         65      1156   17.8
88     кзнецов   кузнецов     1         65      2492   38.3
89     смирова   смирнова     1         65      1885   29.0
90       белво      белов     1         64       930   14.5
91     колзова    козлова     1         64      1445   22.6
94   кзунецова  кузнецова     1         63      2805   44.5
95      поп*ва     попова     1         63      1579   25.1
98      козлво     козлов     1         63      1420   22.5
99      попов*      попов     1         63      1447   23.0
100   кзнецова  кузнецова     1         63      2805   44.5
101    см*рнов    смирнов     1         62      1807   29.1
102     пвлова    павлова     1         62      1106   17.8
103   волчкова    волкова     1         62      1619   26.1
104     козло*     козлов     1         62      1420   22.9
105    петроав    петрова     1         61      1367   22.4
106    во*кова    волкова     1         61      1619   26.5
107    смирн*в    смирнов     1         61      1807   29.6
108    волков*    волкова     1         61      1619   26.5
110     волокв     волков     1         61      1506   24.7
112     егрова    егорова     1         61      1193   19.6
113  кузнец*ва  кузнецова     1         60      2805   46.8
114     блеова     белова     1         60      1016   16.9
115    кролева   королева     1         60       967   16.1

In [12]:
orcs = apply_corrections_verbose(orcs, 'surname', correction_map_sur, "ORCS")
employees = apply_corrections_verbose(employees, 'surname', correction_map_sur, "EMPLOYEES")

=== ПРИМЕНЕНИЕ: ORCS [surname] ===
  📝 Строк изменено:      3339
  📊 Уникальных ДО:       45391
  📊 Уникальных ПОСЛЕ:    42240
  📉 Сжатие словаря:      -3151 (столько дублей устранено)
------------------------------
=== ПРИМЕНЕНИЕ: EMPLOYEES [surname] ===
  📝 Строк изменено:      255738
  📊 Уникальных ДО:       885674
  📊 Уникальных ПОСЛЕ:    791158
  📉 Сжатие словаря:      -94516 (столько дублей устранено)
------------------------------

In [13]:
# 2. ФИНАЛЬНОЕ СОХРАНЕНИЕ
print("\n=== СОХРАНЕНИЕ CLEAN_V2 (FINAL) ===")

# Сохраняем в Parquet для следующего этапа (Deduplication)
orcs.to_parquet('orcs_clean_v2.parquet', index=False)
employees.to_parquet('employees_clean_v2.parquet', index=False)

print("Файлы v2 сохранены:")
print(f"1. orcs_clean_v2.parquet ({len(orcs)} строк)")
print(f"2. employees_clean_v2.parquet ({len(employees)} строк)")
print("\nЭтап 'Словарная нормализация' завершен.")
print("Теперь нажми 'Save Version' -> 'Save & Run All' и переходи к следующему ноутбуку.")

=== СОХРАНЕНИЕ CLEAN_V2 (FINAL) ===
Файлы v2 сохранены:
1. orcs_clean_v2.parquet (47633 строк)
2. employees_clean_v2.parquet (2011759 строк)

Этап 'Словарная нормализация' завершен.
Теперь нажми 'Save Version' -> 'Save & Run All' и переходи к следующему ноутбуку.